

name: Deploy to VPS # Name of your action

on:
  push:
    branches: [ main ] # Essentially it only triggers on push events on the main branch. Branches is an array

jobs:
  deploy:

    runs-on: [self-hosted, linux] # So these are the flags or whatever for your self hosted runner

    if: "contains(github.event.head_commit.message, '[deploy]')" # If the commit title contains "[deploy]" then proceed

    steps:
      - uses: actions/checkout@v2 # idk what this is used for tbh but it's needed I think
      - name: Add secrets to .env # This whole section only adds env vars to a file
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
          SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
          GENIUS_ACCESSTOKEN: ${{ secrets.GENIUS_ACCESSTOKEN }}
          NSFAI_KEY: ${{ secrets.NSFAI_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

          # API stuff
          API_SERVER: ${{ secrets.API_SERVER }}
          AUTH_B64: ${{ secrets.AUTH_B64 }}
          AUTH_USER: ${{ secrets.AUTH_USER }}
          AUTH_PASS: ${{ secrets.AUTH_PASS }}
          AUTH_USERAGENT: ${{ secrets.AUTH_USERAGENT }}

          # Webhooks for stuff
          SUGGESTION_WEBHOOK: ${{ secrets.SUGGESTION_WEBHOOK }}
          REGULAR_WEBHOOK: ${{ secrets.REGULAR_WEBHOOK }}
          IFTTT_WEBHOOK: ${{ secrets.IFTTT_WEBHOOK }}
          SHARD_WEBHOOK: ${{ secrets.SHARD_WEBHOOK }}

        run: |
          echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> .env
          echo "SPOTIFY_ID=$SPOTIFY_ID" >> .env
          echo "SPOTIFY_SECRET=$SPOTIFY_SECRET" >> .env
          echo "GENIUS_ACCESSTOKEN=$GENIUS_ACCESSTOKEN" >> .env
          echo "NSFAI_KEY=$NSFAI_KEY" >> .env
          echo "RAPIDAPI_KEY=$RAPIDAPI_KEY" >> .env
          echo "API_SERVER=$API_SERVER" >> .env
          echo "AUTH_B64=$AUTH_B64" >> .env
          echo "AUTH_USER=$AUTH_USER" >> .env
          echo "AUTH_PASS=$AUTH_PASS" >> .env
          echo "AUTH_USERAGENT=$AUTH_USERAGENT" >> .env
          echo "SUGGESTION_WEBHOOK=$SUGGESTION_WEBHOOK" >> .env
          echo "REGULAR_WEBHOOK=$REGULAR_WEBHOOK" >> .env
          echo "IFTTT_WEBHOOK=$IFTTT_WEBHOOK" >> .env
          echo "SHARD_WEBHOOK=$SHARD_WEBHOOK" >> .env
          echo "APIACCESS=true" >> .env
        #  echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> .env
      
      - name: Install dependancies
        run: yarn
      
      - name: Run karen-bot
        run: pm2 stop krn-bot-gh && pm2 start app.js --name krn-bot-gh
